const supabaseUrl = 'https://pmapkowimesplgbvrook.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtYXBrb3dpbWVzcGxnYnZyb29rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MTUwNzYsImV4cCI6MjA3ODM5MTA3Nn0.5_jdBZfEHMq4thAe9UnmDOzAhQRq_9QclnEIjbaoj0M';

export const supabaseClient = supabase.createClient(supabaseUrl, supabaseKey);
